services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ocpp_backend
    environment:
      DATABASE_URL: sqlite+aiosqlite:///./data/ocpp16.db
    volumes:
      - ocpp_db:/app/data
    networks:
      - default
      - coolify
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ocpp_frontend
    depends_on:
      - backend
    networks:
      - default
      - coolify
    restart: always

volumes:
  ocpp_db:

networks:
  coolify:
    external: true
